name: plugin-cdd-java
description: Plugin que avalia código Java usando a abordagem do CDD
display-name: plugin-cdd-java
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: README.md
usage: documentacao-plugin-cdd.md.md
types:
  - app
hooks:
  - type: run-script
    trigger: before-render
    script: script.py
